# Goals:
# 1. formulate a simple navigation problem as a search problem;
# 2. identify states, actions, transitions, initial states, goals, and costs;
# 3. explain the difference between blind and informed search;
# 4. describe the role of a heuristic in A* search;
# 5. use an LLM to assist in implementing a search algorithm;
# 6. test and validate code generated by an LLM;
# 7. compare the behaviour of search algorithms using appropriate measures;
# 8. reflect critically on the use of an LLM as an engineering tool.
"""
State S = {currX, currY}
Actions A = {Up, Down, Left, Right}
Transition Function = {((x,y),(nx,ny)): manhattan_dist((x,y), (nx,ny))==1 && grid[nx][ny]!='#'}
s0 = (x,y) of S
G = {(x,y): grid[x][y] = 'G'}
c = Number of steps taken

---------------------------------
A* as BFS+Greedy
Heuristic as manhattan distance
f(n) = g(n) + h(n)
Minheap is based on f(n)

Admissibility: h(n) <= actualdist
-------
PROBLEM:
Scenario: Warehouse Robot Navigation
Imagine a small autonomous robot operating in a warehouse.
The robot must move from a loading area to a delivery area. Some parts of the warehouse are
blocked by shelves.
The robot can move one cell at a time:
Up, Down, Left, Right.
Every movement has cost 1.
The warehouse is represented by the following ASCII map.
3
Artificial Intelligence Laboratory: Search
#################
#S....#.........#
#.###.#.#######.#
#...#.#.......#.#
###.#.#######.#.#
#...#.........#.#
#.###########.#.#
#.............#G#
#################
The symbols have the following meanings:
Symbol Meaning
# Obstacle
. Free cell
S Starting position
G Goal position
Your task is to construct an agent that finds a path from S to G

Design for search agent:
State, as mentioned, is {currX, currY}
Warehouse: 2D matrix
Valid actions: Finding adjacent coords within bounds and checking
Recognition: If currX,currY has grid value as G
Information in frontier: Assuming frontier means minheap, then:
bfs: anything is fine
A*: the node with least heuristic
Reconstruction: We can use parent pointers

RECORD:
1. Was a solution found?
2. What is the solution path
3. What is the path length
4. How many states were expanded

Answering these questions and keeping the design in mind, generate Python code for A*, BFS, DFS, and Greedy Best-First
Use Tkinter for a visualization

Use manhattan distance as the heuristic
"""

from collections import deque
import heapq
from typing import List, Tuple, Optional, Dict


# The warehouse map
MAP = [
    "#####################",
    "#S....#............G#",
    "#.##....##########..#",
    "#....##.............#",
    "#.######.###.#.###..#",
    "#........#..........#",
    "#####################"
]


class WarehouseSolver:
    def __init__(self, grid: List[str]):
        self.grid = grid
        self.rows = len(grid)
        self.cols = len(grid[0])
        self.start: Optional[Tuple[int, int]] = None
        self.goal: Optional[Tuple[int, int]] = None
        
        # Locate Start and Goal
        for r in range(self.rows):
            for c in range(self.cols):
                if grid[r][c] == 'S':
                    self.start = (r, c)
                elif grid[r][c] == 'G':
                    self.goal = (r, c)

    def get_neighbors(self, pos: Tuple[int, int]) -> List[Tuple[int, int]]:
        r, c = pos
        neighbors = []
        directions = [(-1, 0), (1, 0), (0, -1), (0, 1)] # Up, Down, Left, Right
        for dr, dc in directions:
            nr, nc = r + dr, c + dc
            if 0 <= nr < self.rows and 0 <= nc < self.cols and self.grid[nr][nc] != '#':
                neighbors.append((nr, nc))
        return neighbors

    def manhattan(self, p1: Tuple[int, int], p2: Tuple[int, int]) -> int:
        return abs(p1[0] - p2[0]) + abs(p1[1] - p2[1])

    def reconstruct_path(self, parent: Dict[Tuple[int, int], Optional[Tuple[int, int]]], current: Tuple[int, int]) -> List[Tuple[int, int]]:
        path = []
        curr: Optional[Tuple[int, int]] = current
        while curr is not None:
            path.append(curr)
            curr = parent[curr]
        path.reverse()
        return path

    def bfs(self):
        frontier = deque([self.start])
        visited = {self.start}
        parent = {self.start: None}
        expanded_nodes = []
        
        while frontier:
            curr = frontier.popleft()
            expanded_nodes.append(curr)
            
            if curr == self.goal:
                return self.reconstruct_path(parent, curr), expanded_nodes
                
            for nxt in self.get_neighbors(curr):
                if nxt not in visited:
                    visited.add(nxt)
                    parent[nxt] = curr
                    frontier.append(nxt)
                    
        return None, expanded_nodes

    def dfs(self):
        frontier = [self.start]
        visited = set()
        parent = {self.start: None}
        expanded_nodes = []
        
        while frontier:
            curr = frontier.pop()
            if curr in visited:
                continue
            
            visited.add(curr)
            expanded_nodes.append(curr)
            
            if curr == self.goal:
                return self.reconstruct_path(parent, curr), expanded_nodes
                
            # Reverse to maintain Up, Down, Left, Right order in stack
            for nxt in reversed(self.get_neighbors(curr)):
                if nxt not in visited:
                    parent[nxt] = curr
                    frontier.append(nxt)
                    
        return None, expanded_nodes

    def greedy(self):
        # Priority Queue stores: (heuristic, count, node)
        count = 0
        frontier = [(self.manhattan(self.start, self.goal), count, self.start)]
        visited = set()
        parent = {self.start: None}
        expanded_nodes = []
        
        while frontier:
            _, _, curr = heapq.heappop(frontier)
            
            if curr in visited:
                continue
                
            visited.add(curr)
            expanded_nodes.append(curr)
            
            if curr == self.goal:
                return self.reconstruct_path(parent, curr), expanded_nodes
                
            for nxt in self.get_neighbors(curr):
                if nxt not in visited:
                    parent[nxt] = curr
                    count += 1
                    heapq.heappush(frontier, (self.manhattan(nxt, self.goal), count, nxt))
                    
        return None, expanded_nodes

    def astar(self):
        # Priority Queue stores: (f_cost, count, node)
        count = 0
        frontier = [(self.manhattan(self.start, self.goal), count, self.start)]
        g_cost = {self.start: 0}
        parent = {self.start: None}
        visited = set()
        expanded_nodes = []
        
        while frontier:
            _, _, curr = heapq.heappop(frontier)
            
            if curr in visited:
                continue
                
            visited.add(curr)
            expanded_nodes.append(curr)
            
            if curr == self.goal:
                return self.reconstruct_path(parent, curr), expanded_nodes
                
            for nxt in self.get_neighbors(curr):
                new_g = g_cost[curr] + 1
                if nxt not in g_cost or new_g < g_cost[nxt]:
                    g_cost[nxt] = new_g
                    parent[nxt] = curr
                    f_cost = new_g + self.manhattan(nxt, self.goal)
                    count += 1
                    heapq.heappush(frontier, (f_cost, count, nxt))
                    
        return None, expanded_nodes

    def render_map_with_path(self, path: Optional[List[Tuple[int, int]]]) -> str:
        """Renders the grid with '*' marking the solution path."""
        display_grid = [list(row) for row in self.grid]
        if path:
            for r, c in path:
                if display_grid[r][c] not in ('S', 'G'):
                    display_grid[r][c] = '*'
        return "\n".join("".join(row) for row in display_grid)


class TerminalUI:
    def __init__(self, solver: WarehouseSolver):
        self.solver = solver
        self.algorithms = [
            ("BFS", self.solver.bfs),
            ("DFS", self.solver.dfs),
            ("Greedy Best-First", self.solver.greedy),
            ("A* Search", self.solver.astar)
        ]

    def display_all(self):
        print("\n" + "=" * 75)
        print("                 WAREHOUSE NAVIGATION AGENT (TERMINAL UI)        ")
        print("=" * 75)

        results = []
        for name, func in self.algorithms:
            path, expanded = func()
            found = path is not None
            path_len = len(path) - 1 if path else None
            results.append((name, found, path_len, len(expanded), path))

        # Print Comparison Summary Table
        print(f"\n{'Algorithm':<20} | {'Solution Found':<15} | {'Path Length':<12} | {'States Expanded':<15}")
        print("-" * 75)
        for name, found, path_len, expanded_count, _ in results:
            found_str = "Yes" if found else "No"
            len_str = str(path_len) if path_len is not None else "N/A"
            print(f"{name:<20} | {found_str:<15} | {len_str:<12} | {expanded_count:<15}")
        print("-" * 75)

        # Print Detailed Visualizations
        for name, found, path_len, expanded_count, path in results:
            print(f"\n>>> {name} Results <<<")
            if found and path:
                print(f"Status: Solution Found!")
                print(f"Path Length (transitions): {path_len} steps")
                print(f"States Expanded: {expanded_count}")
                print(f"Visual representation of the path (* marks path):")
                print(self.solver.render_map_with_path(path))
                print("\nPath Coordinates (row, col):")
                print(" -> ".join([f"({r},{c})" for r, c in path]))
            else:
                print("No path found.")
            print("-" * 75)


def main():
    solver = WarehouseSolver(MAP)
    ui = TerminalUI(solver)
    ui.display_all()


if __name__ == "__main__":
    main()